# Generated by Django 5.0.6 on 2024-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='uploads/blog-2.jpg', null=True, upload_to='uploads/'),
        ),
    ]
