# Generated by Django 5.0.6 on 2024-06-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_category_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
